### ISSUE TITLE
double import running intrinsic recombination models

### ISSUE THREAD

**Issue by robertdumbrell** [MK8J/semiconductor#2]
Running this code:

```
import numpy as np
from  semiconductor.recombination import intrinsic as intr

Aug_C = intr.Auger(material='Si')

print Aug_C.available_models()
```

I get the error message:

```
Traceback (most recent call last):
  File "/Users/Bob/Dropbox/PhD/Code/auger_lt.py", line 2, in <module>
    from  semiconductor.recombination import intrinsic as intr
  File "/usr/local/lib/python2.7/site-packages/semiconductor/__init__.py", line 4, in <module>
    from . import electrical
  File "/usr/local/lib/python2.7/site-packages/semiconductor/electrical/__init__.py", line 2, in <module>
    from .mobility import Mobility
  File "/usr/local/lib/python2.7/site-packages/semiconductor/electrical/mobility.py", line 14, in <module>
    from . import mobilitymodels as model
  File "/usr/local/lib/python2.7/site-packages/semiconductor/electrical/mobilitymodels.py", line 5, in <module>
    from semiconductor.general_functions import carrierfunctions as GF
  File "/usr/local/lib/python2.7/site-packages/semiconductor/general_functions/carrierfunctions.py", line 5, in <module>
    from semiconductor.material.intrinsic_carrier_density import IntrinsicCarrierDensity as NI
  File "/usr/local/lib/python2.7/site-packages/semiconductor/material/__init__.py", line 4, in <module>
    from .bandgap import BandGap
  File "/usr/local/lib/python2.7/site-packages/semiconductor/material/bandgap.py", line 7, in <module>
    from semiconductor.material.bandgap_narrowing import BandGapNarrowing
  File "/usr/local/lib/python2.7/site-packages/semiconductor/material/bandgap_narrowing.py", line 12, in <module>
    from semiconductor.general_functions import carrierfunctions as GF
ImportError: cannot import name carrierfunctions
```

Running v0.2.0.dev0 installed with pip from the wheel on OSX 10.10.5

**Comment by MK8J** [comment]
Thanks for the bug! 

This is only affecting python 2.7, so not going to jump to the top of my to do list. 
This is an example of why the code needs some refactoring; need to remove these cross imports.
